import {
  LOGGER_ADD,
  NATS_MESSAGE_ADD,
  NATS_RESPONSE_ADD,
  NATS_STATUS_CONNECTED,
  NATS_SUBJECT_ADD
} from './constants.ts';

const events = [
  LOGGER_ADD,
  NATS_MESSAGE_ADD,
  NATS_RESPONSE_ADD,
  NATS_SUBJECT_ADD,
  NATS_STATUS_CONNECTED,
];

export default events;
